### PR TITLE
Add loops for pse image/document. Fix #1098 and #1122

### LINKED ISSUE #1098: Product combinations and associated images
In combination builder you can set a different image for every combination (for example a color), but when you visit the product page and choose for a specific combination, the product image does not change to the one you've setted in builder.
Neither you see the correct image in the cart preview or during the checkout process..
Is it supposed to work this way? any clue how to fix this bug?

### PR DESCRIPTION
**Pull request by lovenunu**

### CODE REVIEW

**Comment by roadster31** [comment]
This PR is conflicting  #1354, which includes fixes for #1098 and #1122

**Comment by gillesbourgeat** [comment]
Why not add a input parameter to the image or document loop ?

**Comment by lovenunu** [comment]
Because #1354 already does it :)

**Comment by gillesbourgeat** [comment]
@lovenunu :+1:

**Pull request merged**
