### PR TITLE
Tinymce fm update

### PR DESCRIPTION
**Pull request by zorn-v**
Fixes https://github.com/thelia/thelia/issues/2426

### CODE REVIEW

**Comment by zorn-v** [comment]
You can investigate it with `diff -qr` on http://responsivefilemanager.com/ and `diff` on `config/config.php`

**Comment by roadster31** [comment]
Why have you changed 321 files ? It's nearly impossible to review the changes ! 

If this PR is about fixing a security breach, please just fix the breach, changing only the files impacted by the breach, and nothing else. I doubt that local/modules/Tinymce/Resources/js/tinymce/filemanager/img/dimension.png and other images are involved in this security breach.

Additionnaly, please be more specific in the title and the description of your PRs, so that one's can understand why you're submitting it.

**Comment by zorn-v** [comment]
> Why have you changed 321 files ?

It's just update "responsive file manager" (http://responsivefilemanager.com/) to latest version with some thelia integrations from current version - checking that you have thelia admin rights and setting paths to `web/media` for uploaded files.

> It's nearly impossible to review the changes !

Actually you need review only `config/config.php`

>> You can investigate it with `diff -qr` on http://responsivefilemanager.com/ and `diff` on config/config.php

```bash
mkdir pr-2427 && cd pr-2427
git clone https://github.com/zorn-v/thelia
cd thelia && git checkout tinymce-fm-update && cd ..
wget https://github.com/trippo/ResponsiveFilemanager/releases/download/v9.11.3/responsive_filemanager.zip
unzip responsive_filemanager.zip
diff -qr filemanager thelia/local/modules/Tinymce/Resources/js/tinymce/filemanager #to make sure that only config/config.php changed
diff filemanager/config/config.php thelia/local/modules/Tinymce/Resources/js/tinymce/filemanager/config/config.php #to review actually changes
```

**Comment by roadster31** [comment]
I've just tested this PR on the master branch.

The image file manager doesn't work if the Thelia installation is in a subdirectory. In this case the URL generated for images and images thumbs is missing the subdirectory : 

img-2017-10-31_10-20-13

Same problem for simple files :

img-2017-10-31_10-21-43

Additionally, thumbs are not displayed in the file manager : 

img-2017-10-31_10-22-53

**Comment by zorn-v** [comment]
Ok, will fix for subfolders.

**Comment by zorn-v** [comment]
Don't forget to remove existing tinymce in web and disable/enable tinymce module before testing.

**Comment by roadster31** [comment]
Oops : this commit https://github.com/thelia/thelia/pull/2427/commits/35ef2e1c90af960e47b117537e599994d4d65919 merges branch master into your PR.

**Comment by zorn-v** [comment]
I was merge it with master by clicking "Update branch" on github (maybe wrong). 
This for simple merge it in master.
Nothing to fix. Just check previous commit.

**Comment by zorn-v** [comment]
It is better by the way. You can check it ob existing codebase.

**Comment by roadster31** [comment]
No, please revert the last commit.

**Comment by zorn-v** [comment]
Ok.

**Comment by roadster31** [comment]
Thank you very much  :simple_smile:

**Comment by zorn-v** [comment]
First - I don't like "-f" in push
Second - when merge, I can differentiate commits and does not break first rule 😄

**Comment by zorn-v** [comment]
You are welcome ;)

**Comment by roadster31** [comment]
Could you please rebase ?

**Comment by zorn-v** [comment]
Done

**Comment by roadster31** [comment]
There is still a problem with the thumbnails when I'm opening the File Manager from the "Insert/edit image" dialog :

img-2017-11-13_10-08-20

The file manager window is opened, but the thumbnails are empty : 

img-2017-11-13_10-06-49

I have to click the file manager "refresh' icon to eventually get the thumbnails : 

img-2017-11-13_10-11-40

img-2017-11-13_10-07-05

I can reproduce the problem with Firefox and Chrome in Windows and Linux, and in IE 11 on Windows.

**Comment by zorn-v** [comment]
Seems lazy loading is buggy. Disabled.

**Comment by roadster31** [comment]
Thanks !

**Pull request merged**
