### PR TITLE
Missing space for selected

### PR DESCRIPTION
**Pull request by InformatiqueProg**

### CODE REVIEW

**Comment by zorn-v** [comment]
What do you think about remember customer selection of limit etc. ?
And by the way, that toolbar must be in one place. (check brand.html search.html view_all.html and maybe I forget something 😄)

**Comment by roadster31** [comment]
Could you please rebase ?

**Comment by InformatiqueProg** [comment]
Done!

**Comment by InformatiqueProg** [comment]
re-rebase done!

**Comment by roadster31** [comment]
Thanks !

**Comment by InformatiqueProg** [comment]
You're welcome!

**Pull request merged**
