### PR TITLE
Update navbar to better ergonomic utilization

### PR DESCRIPTION
**Pull request by mespeche**
- New hamburger icon
- New background color for navbar (better differentiation with topbar)
- Absolute position (allow scroll of navbar)
- Fix collapse bug on close navbar

### CODE REVIEW

**Comment by lunika** [comment]
The tooltips on order and tools are not required. With the dropdown it's not possible to see them.

**Comment by lunika** [comment]
When you expand order or tools menu, there is no background at the end of the page

back office home thelia back office

**Comment by mespeche** [comment]
Normally everything is good !

**Comment by lunika** [comment]
:+1:

**Comment by roadster31** [comment]
A tool-like icon (such as this [wrench] (http://fortawesome.github.io/Font-Awesome/icon/wrench/)) would be better for the "Tools" menu.

The "gear" icon is more suitable for the configuration option.

A [plug] (http://fortawesome.github.io/Font-Awesome/icon/plug/) would be nice for the plugins, instead of the current one.

What do you yhink ?

**Pull request merged**
