### PR TITLE
BackOffice hide module-install if auth are not right

### PR DESCRIPTION
**Pull request by InformatiqueProg**

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Your commit have a strange name ;) [commit bidon](https://github.com/InformatiqueProg/thelia/commit/91d83ca1e295a2a3c8b457124aa59302565846cb)

**Comment by InformatiqueProg** [comment]
Gugule say make a "commit bidon" to restart scrutinizer... 
et ça marche pas en plus ;-)

**Comment by gillesbourgeat** [comment]
ok; can you remove this commit.

**Comment by gillesbourgeat** [comment]
Thanks !

**Pull request merged**
