### PR TITLE
Add manual order in attributeCombination loop

### PR DESCRIPTION
**Pull request by InformatiqueProg**
See PR #1679 and Issue #1678

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Hello,

Can you please complete the Thelia documentation.
https://github.com/thelia/thelia.github.io
Specify the version with the from_version argument
Exemple : 
https://github.com/gillesbourgeat/thelia.github.io/commit/d00dbe038c0a3b4198e2d5f276b0f02b5fbb3603

Thanks !

**Comment by InformatiqueProg** [comment]
I'll do it,
from Thélia 2.3 and 2.2.2 ?

**Comment by gillesbourgeat** [comment]
Your pull request is an improvement, so 2.3.

**Comment by gillesbourgeat** [comment]
Thanks !

**Pull request merged**
