### PR TITLE
Import/export complete rework

### PR DESCRIPTION
**Pull request by bilhackmac**
This PR is a full rework of import/export.
What I do :

externalize import/export logic from controller
aim the lowest memory footprint during export.
add possibility to import and export from console

### CODE REVIEW

**Comment by roadster31** [comment]
That's nice ! Does this rework will address the main export problem: export data stored in memory, which make the export unusable when a lot of data has to be exported (see #1352) ?

**Comment by bilhackmac** [comment]
Yes it's one of my objective

**Comment by roadster31** [comment]
:+1:

**Comment by bilhackmac** [comment]
Ping @gillesbourgeat

**Comment by bibich** [comment]
:+1:
Could you please write a little description for your PR which summarizes the changes.

**Comment by bilhackmac** [comment]
This PR is a full rework of import/export.
What I do :
 - externalize import/export logic from controller
 - aim the lowest memory footprint during export.
 - add possibility to import and export from console

**Comment by roadster31** [comment]
Did you updated the documentation ?

**Comment by gillesbourgeat** [comment]
@roadster31 Can you create an issue please.

**Pull request merged**
