### PR TITLE
Docker integration

### PR DESCRIPTION
**Pull request by lunika**
Hi,

I created a [docker](https://docker.com) configuration and it uses [docker compose](http://docs.docker.com/compose/).

I use only docker since beginning of july for working on Thelia. On one of my computer I don't have php, mysql, apache installed, only docker.

How to start the configuration : 

```
docker-compose up -d
```

tip : create an alias for docker-compose, it's boring to write it all the time

All the script are launched through docker. For examples : 

```
docker exec -it thelia_web_1 php Thelia cache:clear
docker exec -it thelia_web_1 php setup/faker.php
docker exec -it thelia_web_1 unit-tests.sh
docker exec -it thelia_web_1 php composer.phar install
```

Database information : 

* host : mariaDB
* login : root
* password : toor

Once started, you can access it with your browser at this url : http://127.0.0.1:8080 and phpmyadmin : http://127.0.0.1:8081

What is missing : 

* confguration for export compression (zip, gzip, etc)

Obviously you can modify all the configuration for your own case, for example the php version or add environment variable for the database configuration. Each time you modify the configuration, you have to rebuild it : 

```
docker-compose build --no-cache
```

### CODE REVIEW

**Comment by lovenunu** [comment]
:+1:

**Comment by lunika** [comment]
The changelog and the readme are up-to-date

**Comment by bibich** [comment]
Great :+1:
Thanks

**Comment by lunika** [comment]
I have another configuration for testing php7 (but not up-to-date with master) : https://github.com/lunika/thelia/tree/docker_php7

**Comment by bibich** [comment]
Could you update the documentation please ?

**Pull request merged**
