### PR TITLE
Fix return jsonResponse and refactoring

### PR DESCRIPTION
**Pull request by gillesbourgeat**
Add "return" for jsonResponse
https://github.com/thelia/thelia/commit/db11b8eb2d4232f2a3094c843ff6c507ae0f100c#diff-a527c0428dabaf5cb05cccecd5611693R68

Refactoring code.
No behavioral changes.

Cheers

### CODE REVIEW

**Comment by roadster31** [comment]
Already fixed in #1455

**Comment by roadster31** [comment]
:+1:

**Comment by lunika** [comment]
Nice, it will be great to change the http status when it's an ajax request. Return a 500 status code if an error occurred (and of course change the way it is used in the template).

Thanks

**Comment by gillesbourgeat** [comment]
@lunika :+1:  and mini refactoring js
No behavioral changes

**Pull request merged**
