### PR TITLE
Added wysiwyg.js hook where it was missing.

### PR DESCRIPTION
**Pull request by roadster31**

### CODE REVIEW

**Comment by lunika** [comment]
Can you rebase your PR with the current master branch ? Without this travis can't work.

Thanks

**Comment by roadster31** [comment]
Done.

**Comment by lunika** [comment]
All your new hooks have the same value for the ```location``` property. Is it normal ?

Thanks

**Comment by roadster31** [comment]
This is fixed.

**Comment by lunika** [comment]
Thanks

**Pull request merged**
