### PR TITLE
Add Cellphone to order address

### PR DESCRIPTION
**Pull request by lopes-vincent**
This PR add the cellphone from customer address to his order address.

### CODE REVIEW

**Comment by lunika** [comment]
Thelia 2.2.0-alpha1 is already released so you can't modify this sql file.

Moreover, the documentation explain how to create and modify the sql files : http://doc.thelia.net/en/documentation/contribute.html#sql-scripts-modification

**Comment by lunika** [comment]
Before changing anything in your PR I suggest you to rebase your branch with the current master branch. The PR #1423 changed lot of thing about sql generation and you will have conflicted after.

**Comment by lunika** [comment]
Great !

Please complete the Readme with this new modificat and then squash your commits and I will merge your PR.

Thanks

**Comment by lopes-vincent** [comment]
I don't understand, which readme?

**Comment by lunika** [comment]
Changelog sorry

**Comment by lopes-vincent** [comment]
Done ;)

**Pull request merged**
