### PR TITLE
Add method to find category path

### PR DESCRIPTION
**Pull request by bilhackmac**

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
:+1:

Can you add [tag @since](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/since.html) and squash your commits

Thanks !

**Comment by bilhackmac** [comment]
Done :+1:

**Comment by bilhackmac** [comment]
Wait before merging… there is a mistake !

**Comment by bibich** [comment]
thanks

**Pull request merged**
