### PR TITLE
Move the prices from a json to a config

### PR DESCRIPTION
**Pull request by ThomasArnaud**
The prices and the freeshipping boolean are now saved in the table module_config.

### CODE REVIEW

**Comment by roadster31** [comment]
There is a still a consistency problem between colissimo config and areas.

As the config is not stored in a table with a FK to the area table, if an area is deleted, the change is not automatically cascaded to Colissimo config, and there's no listener to handle the change in Colissimo.

**Comment by ThomasArnaud** [comment]
Thanks for your comment, I added a listener to handle the deletion of an area in the config.

**Comment by roadster31** [comment]
:+1:

**Comment by bibich** [comment]
Thanks Céline

**Pull request merged**
