### PR TITLE
Adding optional parameters CC and BCC

### PR DESCRIPTION
**Pull request by zzuutt**
Adding optional parameters CC and BCC in the
- sendEmailMessage function
- createEmailMessage function

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Hello,
Car you fix the scrutinizer issues https://scrutinizer-ci.com/g/thelia/thelia/inspections/bce32439-f4de-45ef-a1d9-786aa1c70268
Thanks !

**Comment by gillesbourgeat** [comment]
Hello,
Can you remove the merge commit 1fdbe54ec727411cf2d39eea5ee3f86f5aaee09c
Thanks !

**Comment by Asenar** [comment]
great ! :+1:

**Comment by zzuutt** [comment]
grr M.... j'ai clique la ou il ne fallait pas
je reviens comment en arriere avec ?
``git reset acd1dfe.....``

**Comment by gillesbourgeat** [comment]
Thanks !

**Pull request merged**
