### PR TITLE
Imagine library updated to 0.6.2

### PR DESCRIPTION
**Pull request by roadster31**
- Imagine library is updated to 0.6.2, which provides a better support for transparency.
- Default border colour of images resized with resize_mode="border" is now transparent instead of opaque white.

### CODE REVIEW

**Comment by lovenunu** [comment]
As the class ```Imagine\Image\Color``` dispear, its potentially BC break for the modules that uses this dependency.

**Comment by roadster31** [comment]
This is the naked truth.

**Comment by lovenunu** [comment]
Well ... Don't care, upgrade is a good thing :D

**Comment by roadster31** [comment]
Well... If we have to write a support class for BC, where should we put it ?

**Comment by lovenunu** [comment]
Nowhere, the ```Imagine``` NS doesn't belong to us.

**Comment by lunika** [comment]
Can you rebase your PR ?

Thanks

**Comment by roadster31** [comment]
OK.

Could you please try to merge PR in chronological order ?

**Pull request merged**
