### PR TITLE
PR Global hook

### PR DESCRIPTION
**Pull request by gillesbourgeat**
# Hello,

## 1 1a0016abeecd75732ef32faa70f6a00c687d60d9
The hook ```account-order.product``` is present in template frontOffice, but not in the database.
https://github.com/thelia/thelia/blob/master/templates/frontOffice/default/account-order.html#L178
This PR fix solves the problem.

## 2 d78c89f491045bbd8bfa3d6e0033fa4ef0965fb2
Remove spaces in sql file insert and update 2.2.0Alpha

## 3 f9899bd9dd73167ca36bf5775af9135a149639fc
Move form seo in template seo

## 4 bc91c49b6af72ecaee4d0935f090602b589f4c08
Add admin hook 
- tab-seo.top
- tab-seo.bottom
- tab-image.top
- tab-image.bottom
- tab-document.top
- tab-document.bottom

## 5 77eed5ee51d019999b8e5ead5f658e22f059748c
Display parameters in SHOW_HOOK
Exemple Exemple
## 6 5cccf626a92d30629e6bd545c36c9aeae8d0984f
Update Changelog

Cheers,

### CODE REVIEW

**Comment by lunika** [comment]
You have to refactor your commit following this PR #1246

**Comment by gillesbourgeat** [comment]
@lunika refactor ok
#1246 is a very good PR

**Comment by lunika** [comment]
Thanks.

Did you use something for generating the description of this PR ?

**Comment by gillesbourgeat** [comment]
No, just my hands, and a minimum my keyboard :)

**Comment by lunika** [comment]
Nice job.

Rebase it and I merge it.

Thanks

**Comment by lovenunu** [comment]
:+1: :clap:

**Comment by gillesbourgeat** [comment]
@lunika Rebase ok

**Pull request merged**
