### PR TITLE
[WIP] Manage product's position in multiple categories

### PR DESCRIPTION
**Pull request by vigourouxjulien**
Manage product's position in multiple categories.

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Hello,
The schema.xml and insert.sql file are missing in your PR.
Can you complete the update file `2.3.0-alpha2` not `2.3.0-alpha1`
It's good idea to deprecate and create a fallback to the all methods which refer for position in `Product Model`
Example :
```php
class Product extends BaseProduct implements FileModelParentInterface
{
   ... more code

    /**
     * {@inheritdoc}
     * @deprecated since version 2.3, was moved in the \Thelia\Model\ProductCategory::setPosition
     */
    public function setPosition($v)
    {
        // create a fallback for backward compatibility

        return parent::setPosition($v);
    }

   ... more code
}
```

This pull request requires a lot of testing
Cheers,

**Comment by Asenar** [comment]
:+1: Thanks you !

**Comment by Asenar** [comment]
I rebased @vigourouxjulien works on current master and done some minor changes in the commit:

* schema.xml modified / thelia.sql generated 
* used `alpha2` instead of `alpha1`

I wasn't sure about how to do the deprecated thing.

This can be found on https://github.com/asenar/thelia/tree/feature/product_categories_position

**Comment by bibich** [comment]
PR #2066 already fixes this issue.
Thanks.

**Pull request closed without merging**
