### PR TITLE
Restructuring of the backoffice display

### PR DESCRIPTION
**Pull request by mespeche**
New menu

capture d ecran 2015-06-11 a 11 28 15

Desktop version

capture d ecran 2015-06-11 a 15 35 06

Mobile version

capture d ecran 2015-06-11 a 15 35 31

### CODE REVIEW

**Comment by roadster31** [comment]
Wow... Nice work !

Could you please change the menubar icons ? We talked about that with @lunika .

A plug for the modules, a gear for the configuration item, a wrench for the tools, and a folder for the... folders,

**Comment by gillesbourgeat** [comment]
:+1:

**Comment by mespeche** [comment]
Thanks !

Yes, we can. I'll see that with our graphic designer ;-)

**Comment by lunika** [comment]
@roadster31 oups I forgot to talk about this subject with @mespeche

**Comment by roadster31** [comment]
Argh, icons are stille the same :disappointed:

**Comment by lunika** [comment]
don't worry,  @mespeche will create other PRs

**Pull request merged**
