### PR TITLE
Update faker to stable version 1.5

### PR DESCRIPTION
**Pull request by gillesbourgeat**
Update faker to stable version 1.5

### CODE REVIEW

**Comment by lovenunu** [comment]
You forgot to update ```setup/composer.json```, and I think you didn't update the ```composer.lock``` too :)

**Comment by gillesbourgeat** [comment]
@lovenunu :+1:

**Comment by lunika** [comment]
If you want to update a library, use composer require with the required version instead of updating manually the composer.json file

**Comment by lunika** [comment]
I ignore how you update the faker but not only the faker was updated. Take a look at the diff on composer.lock file.

smarty's source has been changed from git to svn but the svn repo for this version does not exists anymore.

Revert all your modification and simply run : 

```
composer require fzaninotto/faker:1.5.*
```

or

```
composer require fzaninotto/faker:~1.5
```

**Comment by gillesbourgeat** [comment]
Yes, I used this commands.
From a new local instance of the thelia repository, I did not have this problem.
Yet, my old local instance is up to date.
Thanks !!!

**Pull request merged**
