### PR TITLE
if the URL contains / and rewriteurl

### PR DESCRIPTION
**Pull request by zzuutt**
if default url is
toto/titi/produit

Url redirected 
tata/titi/produit-blalbla

url returned
www.site.fr/tata/titi/toto/titi/produit

the correct url
www.site.fr/toto/titi/produit

### CODE REVIEW

**Comment by roadster31** [comment]
What about tutu ?

**Comment by zzuutt** [comment]
:stuck_out_tongue_winking_eye:

**Comment by lunika** [comment]
most of this url is an absolute url so you can't put a slash at the beginning

**Comment by zzuutt** [comment]
It must be set at the level of the module rewriteurl?

**Comment by lunika** [comment]
Do you have mutli domain activated ? (one domain for each language ?)

**Comment by gillesbourgeat** [comment]
Hello,

t's the same discussion

http://thelia.net/forum/viewtopic.php?pid=65910#p65910

**Comment by zzuutt** [comment]
hello,
Lunika : no / I have just one language 'french' - one domain
GillesBourgeat : yes, 

it is better to continue to discuss on the forum

**Comment by lunika** [comment]
I clone this PR, it is impossible to merge it.

Thanks

**Pull request closed without merging**
