### PR TITLE
cod 

### PR DESCRIPTION
**Pull request by pamperop**
cash on delivery module can anyone create ?

### CODE REVIEW

**Comment by lovenunu** [comment]
I don't understand your pull request at all. Could you explain what you wanted to do ?

**Comment by pamperop** [comment]
Adds Cash on Delivery + Fee payment method to your payments list. You can select the type of the fee (percentage or fixed amount). You can select the shipping methods where you want it active.

Features:
 Adds cash on delivery with customizable fee feature to the payment and order totals methods
 You can choose if the fee type should be a fixed amount or percentage
 You can select for which store will it be available.
 You can choose if the fee type should be a fixed amount or percentage

you can check smilat things online here http://bit.ly/1ISYw2V

**Comment by roadster31** [comment]
@lovenunu , this is not a PR, but a feature request.

@pamperop, please use the [http://thelia.net/forum] (Thelia forum) for getting support, and the [https://github.com/thelia/thelia/issues] (issues) for feature requets.

Thanks.

**Comment by lunika** [comment]
This feature must be a modue and not a native feature, so please create a module.

**Pull request closed without merging**
