### PR TITLE
Continue backoffice new style

### PR DESCRIPTION
**Pull request by mespeche**
__New login page :__

capture d ecran 2015-07-10 a 15 35 16

__New home page :__

home

### CODE REVIEW

**Comment by fluppi** [comment]
Great !

**Comment by roadster31** [comment]
:heart_eyes:

**Comment by gillesbourgeat** [comment]
:+1:

**Comment by gillesbourgeat** [comment]
The alerts exceed width on the page wrapper

edit product thelia back office

**Comment by mespeche** [comment]
@gillesbourgeat It's a mistake of the VirtualProductControl module.

**Comment by nicolasleon** [comment]
Loving it!!

**Comment by gillesbourgeat** [comment]
Thanks !!

**Comment by roadster31** [comment]
Any plans to change the menu icons ?

**Pull request merged**
