### PR TITLE
Avoid having too many results in the backoffice search page

### PR DESCRIPTION
**Pull request by gillesbourgeat**
This pull request fix to 25 the number of search results by type to avoid too long loading times or of memory overflow.

### CODE REVIEW

**Comment by roadster31** [comment]
Is it possible to add a notice when more than 25 results are available ?

**Comment by gillesbourgeat** [comment]
@roadster31 This requires making additional queries that are very greedy in this page.
Why not, an under search that allowing of paginate the results of a type if the number of results returned by the loop is equals 25.
This under search is accessed by a link under the search of the first list.
This feature will be for Thelia 2.4.

**Comment by roadster31** [comment]
@gillesbourgeat to achieve this without additional queries, limit the loop to 26 instead of 25, hide the 26th result with a Smarty test, and check if ($LOOP_COUNT > 25).

**Comment by gillesbourgeat** [comment]
@roadster31 ok, but for now there will be just a message and not a link allowing paginate the search.

**Comment by roadster31** [comment]
Sure. This is just a workaround to the lack of pagination, to warn the user that only the first 25 results are displayed.

**Comment by gillesbourgeat** [comment]
@roadster31 Done ! This suits your ?

**Comment by roadster31** [comment]
Wonderful :heart:

**Pull request merged**
