### PR TITLE
fix #2087, check in db if current admin exists

### LINKED ISSUE #2087: the session is style active after an admin is deleted
I tested that issue on both 2.2.2 and master branch.

I created 2 admins: `user1` and `user2`, and logged in with both on them from 2 different browser (firefox and firefox, with 2 differents profiles)

logged with `user1`, I deleted `user2`
`user2` has still full access to the admin.

I also tried to remove all cache but the session seems only cookie dependant.

### PR DESCRIPTION
**Pull request by Asenar**
This commit checks if the current logged in admin (from session) still
exists in the database, and if the password has not changed.

### CODE REVIEW

**Comment by Asenar** [comment]
This fixes #2087

**Comment by patrick-mcdougle** [comment]
With the symfony security component, the AbstractToken has a `hasUserChanged()` method that is supposed to take care of this. Does Thelia use/extend the AbstractToken?

**Comment by Asenar** [comment]
Hi, I suppose it does, feel free to commit the fix, and mention the issue 2087 in the log message.

**Comment by bibich** [comment]
It would be preferable to implement your checking in the `getAdminUser` method, maybe with a caching system.

**Comment by Asenar** [comment]
The problem is precisely the current method which uses a cache somewhere (I don't know well symfony), with the consequence of a deleted admin can still do anything he wants (including creating an other admin) if his session is still active (and same problem for customers but my solution doesn't work :/ )

**Comment by TomPradat** [comment]
Why not deleting the session of this admin when we delete the admin from the backoffice ? Would solve all problems and not add additionnal controls

**Comment by roadster31** [comment]
Discussion (and fixes) continue in PR #2359

**Pull request closed without merging**
