### PR TITLE
PHP>=7.1 fixes

### PR DESCRIPTION
**Pull request by zorn-v**

### CODE REVIEW

**Comment by zorn-v** [comment]
Unfortunately propel is not fully compatible with 7.2
I like changes in php 7.2 coz that pieces of code in propel when php throw notice, looks like a shit 😄 
I know that is late to change ORM (BYW I like it... outside), but something must be do.

**Comment by roadster31** [comment]
We will not replace Propel by another ORM. 

Please report the 7.2 compatibility problem at the propel repository https://github.com/propelorm/Propel2

**Comment by zorn-v** [comment]
> We will not replace Propel by another ORM.

I know it, and say it. In propel repo anarchy I think.
Alpha "status" (thru years) untie the hands :smile:

**Comment by roadster31** [comment]
This PR was included in #2422

**Pull request closed without merging**
