### PR TITLE
Ability to remove arguments in a loop

### PR DESCRIPTION
**Pull request by air-dex**
It is possible to add arguments for a loop but it is not possible to remove them, just like for forms. This PR enables Thelia to do such a thing.

### CODE REVIEW

**Comment by lunika** [comment]
ok, can you do it @air-dex ?

**Comment by air-dex** [comment]
Done.

**Comment by lunika** [comment]
Can you complete the changelog please ?

Thanks

**Comment by air-dex** [comment]
Done

**Pull request merged**
