### PR TITLE
all Thelia files are EOF unix style + fix email admin

### PR DESCRIPTION
**Pull request by Asenar**
end.php is now unix style instead of dos

### CODE REVIEW

**Comment by bibich** [comment]
in fact all these files are in dos EOL : 

- web/install/connection.php
- web/install/end.php
- web/install/config.php
- web/install/bdd.php
- web/install/permission.php
- web/install/header.php
- web/install/bootstrap.php

could you convert them too ?

**Comment by Asenar** [comment]
I converted end.php because I edited it, but sure :)

**Comment by bibich** [comment]
Oops I havn't seen your real modification (line 64) as all lines was in red in the diff.
sorry :)

**Comment by gillesbourgeat** [comment]
Thanks !

**Pull request merged**
