### PR TITLE
check current stable release

### PR DESCRIPTION
**Pull request by Asenar**

### CODE REVIEW

**Comment by Asenar** [comment]
Should I change the backOffice/home template to use a local request related to `Thelia/Install/Update->getWebVersion()` ?

**Comment by Asenar** [comment]
I rebased what I've done over #1965 then rebased all on current master :)

That PR now uses `Version::parse()` to secure the response of version.php

**Comment by gillesbourgeat** [comment]
Informations for my commits.

Fixes an undesirable behavior of the pull request #1788

This pull request deletes all Adminincludes unseless in the core modules, and also adds the ability to display messages from the update file.

After the update 2.3.0-alpha1, composer does not deleted the "Adminincludes". So, the module interfaces were duplicated

**Comment by gillesbourgeat** [comment]
Thanks !

**Pull request merged**
