### PR TITLE
tinymce plugin fullscreen fix

### PR DESCRIPTION
**Pull request by InformatiqueProg**
Resolve bug: navbar is over tinymce in fullscreen mode

### CODE REVIEW

**Comment by Soldras** [comment]
:+1:

**Comment by gillesbourgeat** [comment]
Hello,
:-1: 
The solution is in css, not in js.
The css class ```.navbar-static-top``` has a bad zIndex.

**Comment by InformatiqueProg** [comment]
I'm agree with you, a CSS correction is better solution (z-index must be less than 100)

**Comment by InformatiqueProg** [comment]
or if need to keep z-index: 1000
body.mce-fullscreen .navbar-static-top {
    display: none;
}

**Comment by gillesbourgeat** [comment]
No, you just have to remove the z-index.
(Must be tested)

**Pull request closed without merging**
