### PR TITLE
Check virtualProduct before send mail

### PR DESCRIPTION
**Pull request by InformatiqueProg**
(already done on Branch 2.2)

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Please, can you update the CHANGELOG for the version 1.6

**Comment by InformatiqueProg** [comment]
That's what you want ?

**Comment by gillesbourgeat** [comment]
Your fork was outdated ?
it is not normal to have the part of 2.1.5 in your commit
https://github.com/InformatiqueProg/thelia/blame/153d10b4a65d825689100380681c8ec4f88b178b/CHANGELOG.md#L4

**Comment by InformatiqueProg** [comment]
Yes, my fork is still in 2.1.4 and i don't if i can update it now...
I can close this PR, and create a new one
or
you can create a PR with this change
It is as you want

**Comment by gillesbourgeat** [comment]
if you followed this method http://doc.thelia.net/en/documentation/contribute.html
```
git checkout master
git pull --ff-only upstream master
git checkout your-branch
git rebase -i master
// fix conflict in changelog with your editor, and save
git add CHANGELOG.md
git rebase --continue
git push -f origin your-branch

or you can make a new pull request

**Comment by gillesbourgeat** [comment]
do you know how to compress your commits ?
want to teach you how to compress your 3 commits in one commit ?

**Comment by InformatiqueProg** [comment]
Yes
Github/Git are great tools but need practice

**Comment by gillesbourgeat** [comment]
Something went wrong, there are 5 commits :/
it is better to create a new pull request
More informations about rebase https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Pull request closed without merging**
