### PR TITLE
Add thelia logger as a service

### PR DESCRIPTION
**Pull request by lovenunu**

### CODE REVIEW

**Comment by roadster31** [comment]
:+1:

**Comment by lovenunu** [comment]
I think I'll have to write some doc to force developpers to use it instead of the singleton

**Comment by roadster31** [comment]
We'll have to deprecate TLog.

And also define a TheliaLoggerInterface.

**Comment by lovenunu** [comment]
We don't need any interface. Tlog currently implements ```Psr\Log\LoggerInterface```, I think we should base our work on that one to integrate Monolog. We could translate destinations into monolog handlers, but the two loggers are so different ... I think it'll be fun to work on that :)

**Comment by roadster31** [comment]
We do, as `TLog::addXXXX() methods are widely used in the code, and are not part of ``Psr\Log\LoggerInterface`

**Comment by roadster31** [comment]
What about the interface ?

**Comment by lovenunu** [comment]
Well, I think that rather writing our own interface, we should deprecate ```addXXX``` methods and remove them when we integrate another logger. What do you think of this @lunika and @bibich ?

**Comment by roadster31** [comment]
Ir's fine for me.

**Pull request merged**
