### PR TITLE
Add hooks for email template

### PR DESCRIPTION
**Pull request by InformatiqueProg**
PR for issue #1660

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Hello,
I'm sorry, i did not say it. For the insert.sql file, there are ranges.
0 - 999 for FrontOffice
1000 - 1999 for BackOffice
2000 - 2999 for PDF
3000 - 3999 for Email

**Comment by InformatiqueProg** [comment]
Ok, i'll change this.
what about email TXT versions ?
new hooks for them too ?

**Comment by gillesbourgeat** [comment]
:+1:
for the html templates : ```email-html.order-confirmation.before-address```
for the txt templates : ```email-txt.order-confirmation.before-address```

**Comment by InformatiqueProg** [comment]
Seems to be good...

**Comment by gillesbourgeat** [comment]
Thanks ! Good contribution !

**Pull request merged**
