### PR TITLE
Cart add missing state

### PR DESCRIPTION
**Pull request by InformatiqueProg**

### CODE REVIEW

**Comment by roadster31** [comment]
Could you please rebase ?

**Comment by InformatiqueProg** [comment]
done!

**Comment by roadster31** [comment]
Could you please rebase again (sorry !)

**Comment by InformatiqueProg** [comment]
re-done 😃

**Comment by roadster31** [comment]
Thank you !

**Comment by InformatiqueProg** [comment]
You're welcome!

**Pull request merged**
