### PR TITLE
A Template Context to ease form error processing

### PR DESCRIPTION
**Pull request by roadster31**
This PR introduces a template context, stored in the parser context, so that a controller may get `the last rendered template, and its parameters.

This is very useful to process form errors, where the current template should be redisplayed without redirecting.

```
return $this->render(
    $this->getParserContext()->getCurrentTemplateContext()->getName(),
    $this->getParserContext()->getCurrentTemplateContext()->getParameters()
);
```

### CODE REVIEW

**Comment by lunika** [comment]
:+1:

**Comment by roadster31** [comment]
This PR is not working, as Hooks also uses the render() method to get template fragments.

**Comment by lunika** [comment]
I have to revert it or you want to complete it ?

**Comment by roadster31** [comment]
I'd like to complete it.

**Comment by roadster31** [comment]
Please revert it.

**Comment by lunika** [comment]
Done

**Pull request merged**
