### PR TITLE
[WIP] Add attribute_availability arg in product loop

### PR DESCRIPTION
**Pull request by lopes-vincent**
Add attribute_availability argument in product loop to filter product by attribute availability.
It works like feature_availability argument.

### CODE REVIEW

**Comment by gillesbourgeat** [comment]
Hello,
Can you please complete the Thelia documentation.
Thanks !

**Comment by gillesbourgeat** [comment]
Hello,

Your PR create an error with this example : 
```
{loop name="product_list" type="product" attribute_availability="1: (1 | 2) , 2:*, 3: 10 | (11&12)"}
    {$ID} <br/>
{/loop}
```
```
PDOException in StatementWrapper.php line 196:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'aa_2.ID' in 'where clause'
```

**Comment by lopes-vincent** [comment]
Ooops sorry, fixed! ;)

**Comment by gillesbourgeat** [comment]
You can use this module

https://github.com/thelia-modules/ProductLoopAttributeFilter

Thnaks !

**Pull request closed without merging**
