### PR TITLE
Carousel update

### PR DESCRIPTION
**Pull request by ThomasArnaud**
The images of the carousel are now saved in the core of Thelia and not in the module.

### CODE REVIEW

**Comment by roadster31** [comment]
Whar do you mean saying "saved in the core of Thelia" ?!

**Comment by roadster31** [comment]
As Carousel is shipped with the Thelia distribution, you should provide the code to migrate existing Carousel installations to the new features (moving images, etc.)

**Comment by ThomasArnaud** [comment]
I wrote an update function that should do that : it copies the carousel images in the new directory if they exist.

**Comment by gillesbourgeat** [comment]
Can you please rebase you pull request.
Thanks

**Comment by gillesbourgeat** [comment]
Hello,
Can you delete the old files after the duplication.

**Pull request merged**
