### PR TITLE
Add param "page_param_name" for pagination.html and update customer-edit tpl

### PR DESCRIPTION
**Pull request by gillesbourgeat**
Hello,
Add param "page_param_name" in pagination.html for several pagination in the same page.
The param "page_param_name" change the name get variable. 
Default name "page".

Exemple : 
```smarty
{include
file = "includes/pagination.html"
loop_ref       = "order-list"
max_page_count = 10
page_param_name = "order_page"
page_url  = "{url path="/admin/customer/update" customer_id=$customer_id}"
}
```
Cheers,

### CODE REVIEW

**Comment by lunika** [comment]
Hi,

do you implement already implement it in the default template ?

**Comment by lunika** [comment]
And can you complete the readme please ?

Thanks

**Comment by gillesbourgeat** [comment]
complete readme or changelog ?

**Comment by lunika** [comment]
Sorry, the changelog.

Thanks

**Comment by gillesbourgeat** [comment]
Hello,

Ok, for the changelog.

Cheers,

**Pull request merged**
