### PR TITLE
Refactor & optimization of default template

### PR DESCRIPTION
**Pull request by mespeche**
1. Add Grunt & Bower configuration (src and dist assets)
	 - Src assets, contain Less files and non minified files.
	 - Dist assets, contain all minified files.
 2. Update Bootstrap & FontAwesome versions
 3. Separation of Thelia structure & Thelia theme
 4. Optimization of Less rules & selectors (put bootstrap classes directly into html instead of using theme in less files)
 5. Use only Bootstrap class type for Thelia components (invented buttons types no longer exist, like .btn-change-address...)
 6. Use cdn when exists and import files from assets if cdn doesn't respond
 7. Update Hooks html classes.

Css before :
- Size without Thelia rules : 131ko
- Size of Thelia rules : 129ko
- Full size : 260ko
- Number of selectors : 4973
- Number of rules : 2663

Css after :
- Size without Thelia : 132ko (update of Bootstrap & FontAwesome)
- Size of Thelia rules : 49ko
- Full size : 181ko
- Number of selectors : 3959
- Number of rules : 2390

Js before : 21ko
Js after : 8ko

### CODE REVIEW

**Comment by lunika** [comment]
Can you create a new sale, activate it with some products to see the render ?

**Comment by lunika** [comment]
I can't choose my payment solution

**Comment by lunika** [comment]
In the footer, the subscribe button is cropped

**Comment by lunika** [comment]
in the footer, links are no more inline

**Comment by mespeche** [comment]
I fixed all the bugs you saw ;-)

**Comment by Lucanis** [comment]
navbar-brand blocks are hidden in sm size

**Comment by lunika** [comment]
I merge this PR, after that everybody can continue to work on this template with new PR.

Thanks

**Pull request merged**
