### PR TITLE
The PaymentModule log default level is now INFO instead of ERROR

### PR DESCRIPTION
**Pull request by roadster31**
And that's all !

### CODE REVIEW

**Comment by lunika** [comment]
It will be better to retrieve the global configuration, what do you think ?

**Comment by roadster31** [comment]
No, as the log configuration is currently hardcoded.

**Comment by lunika** [comment]
It is possible to retrieve this specific configuration from the database, no ?

**Comment by roadster31** [comment]
Yes, maybe in the future.

**Comment by lunika** [comment]
The idea is to add the ability to change dynamically the log level using the existing ```tlog_level``` entry in the config table like this : 

```
$this->log->setLevel(ConfigQuery::read('tlog_level',Tlog::INFO));
```

Can you please complete the changelog ?

Thanks

**Comment by roadster31** [comment]
Done !

**Comment by roadster31** [comment]
Well, func. tests failed on 2 of 3 builds, still can't restart them. Can you do it for me @lunika please ?

**Comment by lunika** [comment]
Thanks

**Pull request merged**
