### PR TITLE
Improve schema

### PR DESCRIPTION
**Pull request by bilhackmac**
Improve customer and newsletter schema

### CODE REVIEW

**Comment by roadster31** [comment]
Don('t forget to update the MySQL Workbench schema (https://github.com/thelia/model)

**Comment by gillesbourgeat** [comment]
Hello,

The Thelia scheme follows one same principle for the names her the unique index. I see no reason to change this for a one table.

The problem is identical for the names of the columns. Why turn them into lowercase ?
In the propel schema, the types are uppercase.
```xml
    <xs:simpleType name="default_datatypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BIT"/>
            <xs:enumeration value="TINYINT"/>
            <xs:enumeration value="SMALLINT"/>
            <xs:enumeration value="INTEGER"/>
            <xs:enumeration value="BIGINT"/>
            <xs:enumeration value="FLOAT"/>
            <xs:enumeration value="REAL"/>
            <xs:enumeration value="NUMERIC"/>
            <xs:enumeration value="DECIMAL"/>
            <xs:enumeration value="CHAR"/>
            <xs:enumeration value="VARCHAR"/>
            <xs:enumeration value="LONGVARCHAR"/>
            <xs:enumeration value="DATE"/>
            <xs:enumeration value="TIME"/>
            <xs:enumeration value="TIMESTAMP"/>
            <xs:enumeration value="BINARY"/>
            <xs:enumeration value="VARBINARY"/>
            <xs:enumeration value="LONGVARBINARY"/>
            <xs:enumeration value="NULL"/>
            <xs:enumeration value="OTHER"/>
            <xs:enumeration value="DISTINCT"/>
            <xs:enumeration value="STRUCT"/>
            <xs:enumeration value="BLOB"/>
            <xs:enumeration value="CLOB"/>
            <xs:enumeration value="REF"/>
            <xs:enumeration value="BOOLEANINT"/>
            <xs:enumeration value="BOOLEANCHAR"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="OBJECT"/>
            <xs:enumeration value="ARRAY"/>
            <xs:enumeration value="ENUM"/>
        </xs:restriction>
    </xs:simpleType>
```
The migration process is not good. It's not possible to directly convert the lang field, because the type is different, this causes a data loss.

**Comment by bilhackmac** [comment]
Ok, this PR now following Thelia standards !

Converting `lang` field DO NOT cause data looses since only "numbers" are stored

**Comment by gillesbourgeat** [comment]
Indeed, I thought that field had a locale for content.

**Comment by gillesbourgeat** [comment]
You must rebase your pull request so that it can be merged.

**Comment by bilhackmac** [comment]
Done

**Comment by roadster31** [comment]
Please update Thelia model https://github.com/thelia/model

**Comment by bilhackmac** [comment]
Done

**Comment by gillesbourgeat** [comment]
Thanks !

**Pull request merged**
