### PR TITLE
Fix where clause in Product Loop results in bad Propel Criterion

### PR DESCRIPTION
**Pull request by Alberttyty**

### CODE REVIEW

**Comment by lopes-vincent** [comment]
Please can you explain why did you do this PR ? and what problem does it fix?
Thanks.

**Comment by Alberttyty** [comment]
Example with promo's products loop :
Criteria->toString()
`WHERE (((((NOT ISNULL(`requested_locale_i18n`.ID) OR NOT ISNULL(`default_locale_i18n`.ID)) AND `is_promo`.PROMO=1) AND NOT ISNULL(`is_promo`.ID)) AND NOT ISNULL(`is_min_stock`.ID)) AND `is_min_stock`.ID=`is_promo`.ID)
AND `product`.`visible`=:p4
AND `is_min_stock`.QUANTITY>=:p5`

become
`WHERE ((((NOT ISNULL(`requested_locale_i18n`.ID) OR NOT ISNULL(`default_locale_i18n`.ID)) AND NOT ISNULL(`is_promo`.ID)) AND NOT ISNULL(`is_min_stock`.ID)) AND `is_min_stock`.ID=`is_promo`.ID)
AND `product`.`visible`=:p4
AND `is_promo`.`promo`=:p5
AND `is_min_stock`.`quantity`>=:p6`

Criteria->getMap()
`Array
(
	[.],
	[product.visible],
	[.`is_min_stock`.QUANTITY>=?],
)`

become
`Array
(
	[.],
	[product.visible],
	[product_sale_elements.promo],
	[product_sale_elements.quantity],
)`

So we can extend the product loop to change the query during the process thanks to Propel CriteriON (Criteria Where Clauses)

I hope it's clear :/

**Comment by lopes-vincent** [comment]
Ok, Thanks ! :)

**Comment by Alberttyty** [comment]
Hi, thanks for this merge but it seems to cause performance troubles. Am so sorry about that :/
I do not understand why, it needs investigation about these complex sql query.
I'll see later :(

I've found another solution for now in a new module i would share later but am not satisfied yet by the where clause string even if it works.

I want to resellers has access to specifics product promo not depending in the actual promo state like in Thelia 1.
So i would get this product_sale_elements.promo criterion to cancel it and add a new where clause properly.

Concretly i would write $event->getModelCriteria()->getCriterion(ProductSaleElementsTableMap::PROMO)->addOr(BasicCriterion)
and not $event->getModelCriteria()->getCriterion('.')->addOr(CustomCriterion)

Am sorry again about this bad PR.

**Comment by lopes-vincent** [comment]
Ok I reverted your PR so let me know if you found a better solution ;)

**Pull request merged**
