### PR TITLE
Fixed module usage check in orders before deleting it

### PR DESCRIPTION
**Pull request by roadster31**
Module usage test was wrong.

### CODE REVIEW

**Comment by lunika** [comment]
This code is modified in #1166 too so I close this PR and merge the other one.

Thanks

**Comment by roadster31** [comment]
Yes, I did not remember how I did to get the changes in 2 PRs.

**Comment by lunika** [comment]
I suppose you start your new branch from this one instead of master branch.

**Comment by roadster31** [comment]
Yes, that's it.

**Pull request closed without merging**
