### PR TITLE
correct order name differences between definition and buildModelCriteria

### PR DESCRIPTION
**Pull request by InformatiqueProg**

### CODE REVIEW

**Comment by roadster31** [comment]
Thanks.

Could you please ensure backward compatibility, by leaving the old `alpha` and `alpha_reverse` values ?

**Comment by InformatiqueProg** [comment]
i have checked before do this PR, all loop "area" don't use order argument

- I'll add `alpha` for backward compatibility
- but why add `alpha_reverse` it wasn't in previous `EnumListType` ?

**Comment by roadster31** [comment]
> but why add alpha_reverse it wasn't in previous EnumListType ?
You're right, sorry.

**Comment by InformatiqueProg** [comment]
Done!

**Comment by roadster31** [comment]
Thanks !

**Comment by InformatiqueProg** [comment]
You're welcome! 😉

**Pull request merged**
