### PR TITLE
Administrator email management and features

### PR DESCRIPTION
**Pull request by roadster31**
This PR is a fix for #1510. It adds an address email to the administrator profile. This address email can now be used to login just like the login name.

An administrator could now recover a lost password, just like a regular customer.

Minor improvement: add a language selector on back-office login page.

### CODE REVIEW

**Comment by bibich** [comment]
Nice :+1: 
It would be great to add an option to deactivate the **lost password** feature.
And please could you generate the SQL for translated languages : `php Thelia generate:sql --locales='de_DE,en_US,es_ES,fr_FR'`

**Comment by roadster31** [comment]
Done !

**Comment by roadster31** [comment]
TODO: integrate admin email input during update process

**Comment by roadster31** [comment]
If an admin log in the BO without a valid email address, he's redirected to its profile, and incited to enter an email address.

img-2016-02-02 13 41 02

**Pull request closed without merging**
